# Generated by Django 4.1.4 on 2022-12-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='publications',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
