# Generated by Django 4.1.3 on 2022-12-31 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producttype_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='publications',
            new_name='prod_type',
        ),
    ]
